package com.yada180.sms.domain;

// Generated Sep 30, 2013 1:04:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * CwtRoster generated by hbm2java
 */
public class CwtRoster implements java.io.Serializable {

	private Long rosterId;
	private long moduleId;
	private long sectionId;
	private long intakeId;
	private String attendFlag;
	private String examScore;
	private String lastUpdatedBy;
	private String lastUpdatedDate;
	private String attendDate;
	private String examDate;
	private String status;
	private Long jobId;
	private Long departmentId;
	private Long supervisorId;

	public CwtRoster() {
	}

	public CwtRoster(long moduleId, long sectionId, long intakeId) {
		this.moduleId = moduleId;
		this.sectionId = sectionId;
		this.intakeId = intakeId;
	}

	public CwtRoster(long moduleId, long sectionId, long intakeId,
			String attendFlag, String examScore, String lastUpdatedBy,
			String lastUpdatedDate, String attendDate, String examDate,
			String status, Long jobId, Long departmentId, Long supervisorId) {
		this.moduleId = moduleId;
		this.sectionId = sectionId;
		this.intakeId = intakeId;
		this.attendFlag = attendFlag;
		this.examScore = examScore;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.attendDate = attendDate;
		this.examDate = examDate;
		this.status = status;
		this.jobId = jobId;
		this.departmentId = departmentId;
		this.supervisorId = supervisorId;
	}

	public Long getRosterId() {
		return this.rosterId;
	}

	public void setRosterId(Long rosterId) {
		this.rosterId = rosterId;
	}

	public long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(long moduleId) {
		this.moduleId = moduleId;
	}

	public long getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(long sectionId) {
		this.sectionId = sectionId;
	}

	public long getIntakeId() {
		return this.intakeId;
	}

	public void setIntakeId(long intakeId) {
		this.intakeId = intakeId;
	}

	public String getAttendFlag() {
		return this.attendFlag;
	}

	public void setAttendFlag(String attendFlag) {
		this.attendFlag = attendFlag;
	}

	public String getExamScore() {
		return this.examScore;
	}

	public void setExamScore(String examScore) {
		this.examScore = examScore;
	}

	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public String getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(String lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getAttendDate() {
		return this.attendDate;
	}

	public void setAttendDate(String attendDate) {
		this.attendDate = attendDate;
	}

	public String getExamDate() {
		return this.examDate;
	}

	public void setExamDate(String examDate) {
		this.examDate = examDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	public Long getSupervisorId() {
		return this.supervisorId;
	}

	public void setSupervisorId(Long supervisorId) {
		this.supervisorId = supervisorId;
	}

}
