package com.yada180.sms.domain;

// Generated Sep 30, 2013 1:04:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * CwtRoster generated by hbm2java
 */
public class CwtRoster implements java.io.Serializable {

	private Long rosterId;
	private Long moduleId;
	private Long sectionId;
	private Long intakeId;
	private String attendFlag;
	private String examScore;
	private String lastUpdatedBy;
	private String lastUpdatedDate;
	private String attendDate;
	private String examDate;
	private String status;
	private Long jobId;
	private Long departmentId;
	private Long supervisorId;
    private String archivedFlag;
    private String rosterDate;
    
	public CwtRoster() {
	}

	public CwtRoster(Long moduleId, Long sectionId, Long intakeId) {
		this.moduleId = moduleId;
		this.sectionId = sectionId;
		this.intakeId = intakeId;
	}

	public CwtRoster(Long moduleId, Long sectionId, Long intakeId,
			String attendFlag, String examScore, String lastUpdatedBy,
			String lastUpdatedDate, String attendDate, String examDate,
			String status, Long jobId, Long departmentId, Long supervisorId, String archivedFlag, String rosterDate) {
		this.moduleId = moduleId;
		this.sectionId = sectionId;
		this.intakeId = intakeId;
		this.attendFlag = attendFlag;
		this.examScore = examScore;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.attendDate = attendDate;
		this.examDate = examDate;
		this.status = status;
		this.jobId = jobId;
		this.departmentId = departmentId;
		this.supervisorId = supervisorId;
		this.archivedFlag = archivedFlag;
		this.rosterDate = rosterDate;
	}

	public Long getRosterId() {
		return this.rosterId;
	}

	public void setRosterId(Long rosterId) {
		this.rosterId = rosterId;
	}

	public Long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Long moduleId) {
		this.moduleId = moduleId;
	}

	public Long getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(Long sectionId) {
		this.sectionId = sectionId;
	}

	public Long getIntakeId() {
		return this.intakeId;
	}

	public void setIntakeId(Long intakeId) {
		this.intakeId = intakeId;
	}

	public String getAttendFlag() {
		return this.attendFlag;
	}

	public void setAttendFlag(String attendFlag) {
		this.attendFlag = attendFlag;
	}

	public String getExamScore() {
		return this.examScore;
	}

	public void setExamScore(String examScore) {
		this.examScore = examScore;
	}

	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public String getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(String lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getAttendDate() {
		return this.attendDate;
	}

	public void setAttendDate(String attendDate) {
		this.attendDate = attendDate;
	}

	public String getExamDate() {
		return this.examDate;
	}

	public void setExamDate(String examDate) {
		this.examDate = examDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	public Long getSupervisorId() {
		return this.supervisorId;
	}

	public void setSupervisorId(Long supervisorId) {
		this.supervisorId = supervisorId;
	}

	public String getArchivedFlag() {
		return archivedFlag;
	}

	public void setArchivedFlag(String archivedFlag) {
		this.archivedFlag = archivedFlag;
	}

	public String getRosterDate() {
		return rosterDate;
	}

	public void setRosterDate(String rosterDate) {
		this.rosterDate = rosterDate;
	}
	

}
