package com.yada180.sms.domain;

// Generated Sep 19, 2013 1:34:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * IntakeJobSkill generated by hbm2java
 */
public class IntakeJobSkill implements java.io.Serializable {

	private Long intakeJobSkillId;
	private Long jobSkillId;
	private Long intakeId;

	public IntakeJobSkill() {
	}

	public Long getIntakeJobSkillId() {
		return intakeJobSkillId;
	}

	public void setIntakeJobSkillId(Long intakeJobSkillId) {
		this.intakeJobSkillId = intakeJobSkillId;
	}

	public Long getJobSkillId() {
		return jobSkillId;
	}

	public void setJobSkillId(Long jobSkillId) {
		this.jobSkillId = jobSkillId;
	}

	public Long getIntakeId() {
		return intakeId;
	}

	public void setIntakeId(Long intakeId) {
		this.intakeId = intakeId;
	}

	
	

}
