package com.yada180.sms.domain;

// Generated Oct 3, 2013 11:59:42 AM by Hibernate Tools 3.4.0.CR1

/**
 * StudentDisciplineHistory generated by hbm2java
 */
public class StudentDisciplineHistory implements java.io.Serializable {

	private long studentDisciplineHistoryId;
	private Long intakeId;
	private String violationArea;
	private String violationType;
	private String violationDate;
	private String warnings;
	private String fines;
	private String additionalConsquences;
	private String comments;
	private String createdBy;
	private String creationDate;

	public StudentDisciplineHistory() {
	}

	public StudentDisciplineHistory(long studentDisciplineHistoryId) {
		this.studentDisciplineHistoryId = studentDisciplineHistoryId;
	}

	public StudentDisciplineHistory(long studentDisciplineHistoryId,
			Long intakeId, String violationArea, String violationType,
			String violationDate, String warnings, String fines,
			String additionalConsquences, String comments, String createdBy,
			String creationDate) {
		this.studentDisciplineHistoryId = studentDisciplineHistoryId;
		this.intakeId = intakeId;
		this.violationArea = violationArea;
		this.violationType = violationType;
		this.violationDate = violationDate;
		this.warnings = warnings;
		this.fines = fines;
		this.additionalConsquences = additionalConsquences;
		this.comments = comments;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
	}

	public long getStudentDisciplineHistoryId() {
		return this.studentDisciplineHistoryId;
	}

	public void setStudentDisciplineHistoryId(long studentDisciplineHistoryId) {
		this.studentDisciplineHistoryId = studentDisciplineHistoryId;
	}

	public Long getIntakeId() {
		return this.intakeId;
	}

	public void setIntakeId(Long intakeId) {
		this.intakeId = intakeId;
	}

	public String getViolationArea() {
		return this.violationArea;
	}

	public void setViolationArea(String violationArea) {
		this.violationArea = violationArea;
	}

	public String getViolationType() {
		return this.violationType;
	}

	public void setViolationType(String violationType) {
		this.violationType = violationType;
	}

	public String getViolationDate() {
		return this.violationDate;
	}

	public void setViolationDate(String violationDate) {
		this.violationDate = violationDate;
	}

	public String getWarnings() {
		return this.warnings;
	}

	public void setWarnings(String warnings) {
		this.warnings = warnings;
	}

	public String getFines() {
		return this.fines;
	}

	public void setFines(String fines) {
		this.fines = fines;
	}

	public String getAdditionalConsquences() {
		return this.additionalConsquences;
	}

	public void setAdditionalConsquences(String additionalConsquences) {
		this.additionalConsquences = additionalConsquences;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
	
	

}
